### ISSUE TITLE
Quick start guide node label incorrect

### ISSUE THREAD

**Issue by jojimt** [confidential-containers/confidential-containers#196]
The sample custom resource has the following:
```
spec:
  ccNodeSelector:
    matchLabels:
      node.kubernetes.io/worker: ""
```
However, the documentation at https://github.com/confidential-containers/confidential-containers/blob/main/quickstart.md#prerequisites calls for label **node-role.kubernetes.io/worker=**
