### ISSUE TITLE
 Error while trying to encrypt container image with skopeo #2288 

### ISSUE THREAD

**Issue by elouanjef** [confidential-containers/confidential-containers#202]
Hi, I am following the quickstart tutorial in order to create an encrypted container image an deploy it as a CoCo workload on CC HW (Intel TDX).
# What I want
The image to be encrypted
# What I got
```
$ OCICRYPT_KEYPROVIDER_CONFIG=ocicrypt.conf skopeo copy --insecure-policy --encryption-key provider:attestation-agent docker://library/busybox oci:busybox:encrypted
FATA[0000] Invalid encryption keys: Provided protocol not recognized 
```
Only having errors, I was wondering if it was the OCICRYPT_KEYPROVIDER_CONFIG variable that was undefined so I tried like this:
```
OCICRYPT_KEYPROVIDER_CONFIG="$(cat ocicrypt.conf)" skopeo copy --insecure-policy --encryption-key provider:attestation-agent docker://library/busybox oci:busybox:encrypted
FATA[0000] Invalid encryption keys: Provided protocol not recognized 
```
# What I did
I followed the tutorial on https://github.com/confidential-containers/confidential-containers/blob/main/quickstart.md, from the beginning to "Encrypting an Image"

coco_keyprovider is running (due to the `docker compose up -d` command mentionned in the tutorial):
```
$ ps aux | grep provider
root      100291  0.0  0.0 621968  2688 ?        Ssl  12:59   0:00 coco_keyprovider --socket 0.0.0.0:50000 --kbs http://kbs:8080 --auth-private-key /etc/private.key
```
PS: I was wondering how was set /etc/private.key because I got nothing here:
```
$ ls /etc/private.key
ls: cannot access '/etc/private.key': No such file or directory
```
My ocicrypt.conf file:
```
{
    "key-providers": {
        "attestation-agent": {
            "grpc": "127.0.0.1:50000"
        }
    }
}
```

# Other
- Is anything else to start/setup ?
- Do I need to run the skopeo command in a specific directory ?
Don't hesitate if you need info! Because I'm possibly missing some important information about my config (sorry about this)
Can anyone help me please ?

**Comment by ToviHe** [comment]
skopeo版本问题，这个我之前也遇到过

**Comment by ToviHe** [comment]
将skopeo版本升一下，我是升级到了1.2.4 就可以了

**Comment by elouanjef** [comment]
Yes, I could figure that too, thanks, an update to older version of skopeo is working

**Comment by Toyken-P** [comment]
> 将skopeo版本升一下，我是升级到了1.2.4 就可以了

你好，请问你了解镜像解密需要怎样配置吗，我使用 skopeo 和 coco keyprovider 加密了一个容器镜像并将其上传到了本地的docker镜像仓，并在guest目录`/etc/`下放置了密钥配置文件`aa-offline_fs_kbc-keys.json`，尝试使用 aa-offline_fs_kbc 来获取密钥并解密镜像。
我使用了以下配置来启动k8s的pod：
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-enc
  annotations:
    io.katacontainers.config_path: "localhost:5000/nginx_enc"
spec:
  runtimeClassName: kata
  containers:
  - name: nginx-test
    image: localhost:5000/nginx_enc
    command:
      - top
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
     - name: docker-reg-secret
  restartPolicy: Never
```
但日志显示以下错误：
```bash
PullImage "localhost:5000/nginx_enc:latest" from image service failed: rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5000/nginx_enc:latest": failed to extract layer sha256:ceb5f16d1891b2ef1eb0f93e47ede3b1dbfa0aaa8e8a6b5852efce6ade6f4d09: failed to get stream processor for application/vnd.oci.image.layer.v1.tar+gzip+encrypted: exec: "ctd-decoder": executable file not found in $PATH: unknown
```
似乎 containerd 尝试解密该镜像但失败了，而显然我们是希望由 kata-agent 来完成镜像解密的工作。
请问是我哪里的配置有误吗？
